### ISSUE TITLE
container-quay-quay.service failed

### ISSUE THREAD

**Issue by sramdane** [disposab1e/okd-lab#20]
Hello,
I am trying to follow the explained steps but when I reach the step "Provision bastion host" I get the following error: 

TASK [Start container-quay-quay.service] ***************************************
│ fatal: [10.0.0.2]: FAILED! => {"changed": false, "msg": "Unable to start service container-quay-quay.service: Job for container-quay-quay.service failed because a timeout was exceeded.\nSee \"systemctl status
│ container-quay-quay.service\" and \"journalctl -xe\" for details.\n"}
│
│ PLAY RECAP *********************************************************************
│ 10.0.0.2                   : ok=58   changed=51   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 

Please see attached systemctl status container-quay-quay.service and journalctl -xe from 10.0.0.2 (Bastion
[bastion output.pdf](https://github.com/disposab1e/okd-lab/files/7513276/bastion.output.pdf)
)

**Comment by disposab1e** [comment]
Did you try to provision the `bastion` host again? 

Quay 3.6.1 is not officially released so I gave `okd_lab_quay_image: quay.io/projectquay/quay:3.6-unstable` (/ansible/vars/vars.yaml) a try. I checked and the image does not change since my latest installation and it worked. 

The logs show that the a container quay-quay is already used. Try to remove the old one with `podman rm quay-quay` and start quay again. Is clair running? What are the logs of `podman logs quay-quay`?

Do you have a Hetzner machine?

**Comment by sramdane** [comment]
Thank you.
I could resolve the issue by starting the service (‘systemctl start container-quay-quay.service’) when the playbooks were waiting for the service to start.

No, this was the first time trying to deploy the OKD Lab.

I managed to deploy the OKD Lab, and everything seemed to be working, but LDAB users login into the console dashboard: none LDAP user can log in to the OKD dashboard. 

I am using a BareMetal, Dell PowerEdge T440 with memory 512 GB and SSD 8TB
Thank you again and kind regards

**Comment by disposab1e** [comment]
> I could resolve the issue by starting the service (‘systemctl start container-quay-quay.service’) when the playbooks were waiting for the service to start.

Do you think it's a timeout problem?

> I managed to deploy the OKD Lab, and everything seemed to be working, 

Great to hear!

> but LDAB users login into the console dashboard: none LDAP user can log in to the OKD dashboard.

Just ask: Did you execute all this playbooks? 
`ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/okd.yml --tags config
` 
> I am using a BareMetal, Dell PowerEdge T440 with memory 512 GB and SSD 8TB Thank you again and kind regards

This should be a perfect machine! :-)

**Comment by sramdane** [comment]
Hello, I will later deploy, starting from zero and will let you know. Thanks again!

**Comment by disposab1e** [comment]
After this step:
`ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/okd.yml --tags complete`

It really takes long until all master/worker are ready. Check with:
`watch -n2 oc get nodes`

**Comment by disposab1e** [comment]
/ansible/okd/roles/okd-env/templates/install-config.yaml.j2

replace `/okd_lab/` with `/okd/`

I have to fix this in the new version but should not prevent you from installing okd.

**Comment by disposab1e** [comment]
`/ansible/okd/roles/okd-config/tasks/main.yml`

Icrease timeout wo wait for LDAP to 360. I saw this takes from time to time much longer.

**Comment by sramdane** [comment]
Hello
I have now redeployed the lab and reached to the following step with error:

[lab@lab lb]$ ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/mirror.yml --tags mirror

PLAY [bastion] *********************************************************************************************************************************************************

TASK [mirror-fcos : Create Fedora CoreOS mirror directory] *************************************************************************************************************
ok: [bastion]

TASK [mirror-fcos : Mirror Fedora CoreOS] ******************************************************************************************************************************
ok: [bastion] => (item={'file': 'live-rootfs.x86_64.img', 'dest': 'rootfs'})
ok: [bastion] => (item={'file': 'live-kernel-x86_64', 'dest': 'vmlinuz'})
ok: [bastion] => (item={'file': 'live-initramfs.x86_64.img', 'dest': 'initrd'})

TASK [mirror-pxe : Publish PXEs] ***************************************************************************************************************************************
ok: [bastion] => (item=52-54-00-7f-0e-c5)
ok: [bastion] => (item=52-54-00-9f-f8-1c)
ok: [bastion] => (item=52-54-00-19-6b-b4)
ok: [bastion] => (item=52-54-00-94-21-a1)
ok: [bastion] => (item=52-54-00-bb-dd-78)
ok: [bastion] => (item=52-54-00-da-a9-27)
ok: [bastion] => (item=52-54-00-f7-84-c9)

TASK [mirror-registry : Create organization] ***************************************************************************************************************************
fatal: [bastion]: FAILED! => {"access_control_allow_headers": "AUTHORIZATION, CONTENT-TYPE, X-REQUESTED-WITH", "access_control_allow_methods": "HEAD, POST, GET, OPTIONS", "access_control_allow_origin": "*", "access_control_max_age": "21600", "changed": false, "connection": "close", "content": "{\"detail\": \"A user or organization with this name already exists\", \"error_message\": \"A user or organization with this name already exists\", \"error_type\": \"invalid_request\", \"title\": \"invalid_request\", \"type\": \"http://quay.okd.example.com/api/v1/error/invalid_request\", \"status\": 400}\n", "content_length": "284", "content_type": "application/json", "date": "Tue, 16 Nov 2021 10:37:20 GMT", "elapsed": 0, "json": {"detail": "A user or organization with this name already exists", "error_message": "A user or organization with this name already exists", "error_type": "invalid_request", "status": 400, "title": "invalid_request", "type": "http://quay.okd.example.com/api/v1/error/invalid_request"}, "msg": "Status code was 400 and not [201]: HTTP Error 400: BAD REQUEST", "redirected": false, "server": "nginx/1.14.1", "status": 400, "url": "https://quay.okd.example.com/api/v1/organization/"}

PLAY RECAP *************************************************************************************************************************************************************
bastion                    : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

[lab@lab lb]$ 

Please can you help?

**Comment by disposab1e** [comment]
Did you clean quay before with:

`ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/mirror.yml --tags cleanup`

This is the wotkflow to start a new install:
```

# Destroy (unprovision) Cluster with Terraform
ansible-playbook ~/github/okd-lab/ansible/okd/cluster.yml --tags destroy

# Cleanup OKD installation environment
ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/setup.yml --tags env-cleanup

# Cleanup Fedora CoreOS, PXE's and Registry Mirrors
ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/mirror.yml --tags cleanup

# Setup OKD installation environment
ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/setup.yml --tags env-setup

# Mirror Fedora CoreOS, PXE's and Registry
ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/mirror.yml --tags mirror

# Setup OKD Installer to use Registry Mirror
ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/setup.yml --tags installer-setup

# Remember kubeadmin password
ssh lab@bastion "cat ~/installer/auth/kubeadmin-password" > ~/github/okd-lab/.secrets/kubeadmin

# Apply (provision) Cluster with Terraform
ansible-playbook ~/github/okd-lab/ansible/okd/cluster.yml --tags apply

# In case the bbotstrap will not boot the first time just destroy and apply again
ansible-playbook ~/github/okd-lab/ansible/okd/cluster.yml --tags destroy
ansible-playbook ~/github/okd-lab/ansible/okd/cluster.yml --tags apply

# Complete OKD installation
ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/okd.yml --tags complete

# Destroy Bootstrap with Terraform
ansible-playbook ~/github/okd-lab/ansible/okd/cluster.yml --tags bootstrap-destroy

# Day-1 OKD configurations with Ansible
ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/okd.yml --tags config


```

**Comment by sramdane** [comment]
YES, I did but it is also failing at cleaning:
[lab@lab lb]$ ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/mirror.yml --tags cleanup

PLAY [bastion] *****************************************************************************************************************************************************************************************

TASK [mirror-fcos : Cleanup Fefora CoreOS mirror directory] ********************************************************************************************************************************************
ok: [bastion]

TASK [mirror-pxe : Cleanup PXEs] ***********************************************************************************************************************************************************************
ok: [bastion] => (item=52-54-00-7f-0e-c5)
ok: [bastion] => (item=52-54-00-9f-f8-1c)
ok: [bastion] => (item=52-54-00-19-6b-b4)
ok: [bastion] => (item=52-54-00-94-21-a1)
ok: [bastion] => (item=52-54-00-bb-dd-78)
ok: [bastion] => (item=52-54-00-da-a9-27)
ok: [bastion] => (item=52-54-00-f7-84-c9)

TASK [mirror-registry : Cleanup organization] **********************************************************************************************************************************************************
fatal: [bastion]: FAILED! => {"changed": false, "connection": "close", "content": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.14.1</center>\r\n</body>\r\n</html>\r\n", "content_length": "173", "content_type": "text/html", "date": "Tue, 16 Nov 2021 11:15:55 GMT", "elapsed": 0, "msg": "Status code was 502 and not [204]: HTTP Error 502: Bad Gateway", "redirected": false, "server": "nginx/1.14.1", "status": 502, "url": "https://quay.okd.example.com/api/v1/organization/okd"}

PLAY RECAP *********************************************************************************************************************************************************************************************
bastion                    : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

[lab@lab lb]$

**Comment by disposab1e** [comment]
Quay is not running I suppose?

**Comment by sramdane** [comment]
No, this error is when cleaning using ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/mirror.yml --tags cleanup

**Comment by disposab1e** [comment]
This playbook cleans the Quay organization via Quay API with Quay Token.

**Comment by disposab1e** [comment]
Did you really provision the bastion host today from scratch?

**Comment by sramdane** [comment]
yes, I really did today. However, I have the pull_secret file not working and I did fix. I now BTW get the following error:

[lab@lab lb]$ ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/mirror.yml --tags mirror

PLAY [bastion] *****************************************************************************************************************************************************************************************

TASK [mirror-fcos : Create Fedora CoreOS mirror directory] *********************************************************************************************************************************************
ok: [bastion]

TASK [mirror-fcos : Mirror Fedora CoreOS] **************************************************************************************************************************************************************
ok: [bastion] => (item={'file': 'live-rootfs.x86_64.img', 'dest': 'rootfs'})
ok: [bastion] => (item={'file': 'live-kernel-x86_64', 'dest': 'vmlinuz'})
ok: [bastion] => (item={'file': 'live-initramfs.x86_64.img', 'dest': 'initrd'})

TASK [mirror-pxe : Publish PXEs] ***********************************************************************************************************************************************************************
changed: [bastion] => (item=52-54-00-7f-0e-c5)
changed: [bastion] => (item=52-54-00-9f-f8-1c)
changed: [bastion] => (item=52-54-00-19-6b-b4)
changed: [bastion] => (item=52-54-00-94-21-a1)
changed: [bastion] => (item=52-54-00-bb-dd-78)
changed: [bastion] => (item=52-54-00-da-a9-27)
changed: [bastion] => (item=52-54-00-f7-84-c9)

TASK [mirror-registry : Create organization] ***********************************************************************************************************************************************************
ok: [bastion]

TASK [mirror-registry : Mirror] ************************************************************************************************************************************************************************
fatal: [bastion]: FAILED! => {"changed": true, "cmd": "oc adm -a ${HOME}/installer/secret.json release mirror --from=quay.io/openshift/okd:4.8.0-0.okd-2021-10-24-061736 --to=quay.okd.example.com/okd/4-8-0-0-okd-2021-10-24-061736 --to-release-image=quay.okd.example.com/okd/4-8-0-0-okd-2021-10-24-061736:4.8.0-0.okd-2021-10-24-061736", "delta": "0:00:00.089153", "end": "2021-11-16 12:33:48.290132", "msg": "non-zero return code", "rc": 1, "start": "2021-11-16 12:33:48.200979", "stderr": "error: unable to retrieve release image info: unable to load --registry-config: error occurred while trying to unmarshal json", "stderr_lines": ["error: unable to retrieve release image info: unable to load --registry-config: error occurred while trying to unmarshal json"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************************************************************************************************************************************
bastion                    : ok=4    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

[lab@lab lb]$

**Comment by disposab1e** [comment]
Hm... when I have problems with mirroring the registry this can sometimes happen because quay.io very often has problems. This is why I mirror before installing. When I have problems like this I clean and mirror again.

**Comment by sramdane** [comment]
Ok, ok I maybe have found the issue....I will let you know when mirroring finishes
in docker i have placed the auth my docker token converted into base64. This was the only difference left compared to when i did deploy the first time. So I changed that to be my user name and password for docker converted into base64

**Comment by disposab1e** [comment]
Great you found it!

**Comment by sramdane** [comment]
[lab@lab lb]$ ansible-playbook -i bastion, ~/github/okd-lab/ansible/okd/mirror.yml --tags mirror

PLAY [bastion] *****************************************************************************************************************************************************************************************

TASK [mirror-fcos : Create Fedora CoreOS mirror directory] *********************************************************************************************************************************************
ok: [bastion]

TASK [mirror-fcos : Mirror Fedora CoreOS] **************************************************************************************************************************************************************
ok: [bastion] => (item={'file': 'live-rootfs.x86_64.img', 'dest': 'rootfs'})
ok: [bastion] => (item={'file': 'live-kernel-x86_64', 'dest': 'vmlinuz'})
ok: [bastion] => (item={'file': 'live-initramfs.x86_64.img', 'dest': 'initrd'})

TASK [mirror-pxe : Publish PXEs] ***********************************************************************************************************************************************************************
changed: [bastion] => (item=52-54-00-7f-0e-c5)
changed: [bastion] => (item=52-54-00-9f-f8-1c)
changed: [bastion] => (item=52-54-00-19-6b-b4)
changed: [bastion] => (item=52-54-00-94-21-a1)
changed: [bastion] => (item=52-54-00-bb-dd-78)
changed: [bastion] => (item=52-54-00-da-a9-27)
changed: [bastion] => (item=52-54-00-f7-84-c9)

TASK [mirror-registry : Create organization] ***********************************************************************************************************************************************************
ok: [bastion]

TASK [mirror-registry : Mirror] ************************************************************************************************************************************************************************
changed: [bastion]

PLAY RECAP *********************************************************************************************************************************************************************************************
bastion                    : ok=5    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

[lab@lab lb]$

**Comment by disposab1e** [comment]
@sramdane When you follow the docs [here](https://github.com/disposab1e/okd-lab/blob/master/docs/quay.md) there should be no issues with quay tokens.

**Comment by disposab1e** [comment]
I close this issue.... see: #23 #22 #21 

Let's switch to [discussions](https://github.com/disposab1e/okd-lab/discussions) for further communications.
