### ISSUE TITLE
terraform/<host>/<host>.yml files missing

### ISSUE THREAD

**Issue by manfredmuth** [disposab1e/okd-lab#6]
# yml files missing

The files I miss in your repo are:

`terraform/<host>/<host>.yml`

I did try your code which is pretty awesome.

But provisioning of hosts fails with error `storage pool default not found`

On the way to debug this I found that the 'virsh pool-list' on a raw lab host installation is empty.
Further on I found that the yml description files you refer to in okd-lab/blob/master/docs/02_sizing.md are missing.

And my assumption is that you placed the storage pool description here in the past.

**Comment by disposab1e** [comment]
@manfredmuth 02_sizing.md fixes on release-0.0.4 branch. Thx for reporting!!

**Comment by disposab1e** [comment]
@manfredmuth The default pool is always available in my installation of CentOS. Did you install with my doxs or do you have your own libvirt installation?

**Comment by disposab1e** [comment]
Fixed with Release 0.0.4
